FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env
COPY . ./
RUN dotnet publish ./DotNet.GitHubAction/DotNet.GitHubAction.csproj -c Release -o out --no-self-contained
LABEL maintainer="David Pine <david.pine@microsoft.com>"
LABEL repository="https://github.com/dotnet/samples"
LABEL homepage="https://github.com/dotnet/samples"
LABEL com.github.actions.name="The name of your GitHub Action"
LABEL com.github.actions.description="The description of your GitHub Action."
LABEL com.github.actions.icon="activity"
LABEL com.github.actions.color="orange"
FROM mcr.microsoft.com/dotnet/sdk:5.0
COPY --from=build-env /out .
ENTRYPOINT [ "dotnet", "/DotNet.GitHubAction.dll" ]
